### ISSUE TITLE
cannot register please help me

### ISSUE THREAD

**Issue by RezaFauzan945** [revoxhere/duco-webservices#36]
when i press the register button its just showing please wait and nothing happend when i check the console with inspect element it has 3 issues

`Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at register:230:12`

`Access to XMLHttpRequest at 'https://server.duinocoin.com/register/?<my username and password send by method get>' from origin 'https://wallet.duinocoin.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`jquery-3.6.0.min.js:2 GET https://server.duinocoin.com/register/?username=
net::ERR_FAILED 502
send @ jquery-3.6.0.min.js:2
ajax @ jquery-3.6.0.min.js:2
S.<computed> @ jquery-3.6.0.min.js:2
getJSON @ jquery-3.6.0.min.js:2
register.onclick @ register.js:30`

**Comment by RezaFauzan945** [comment]
thankyou very much

**Comment by LDarki** [comment]
Hi,
```Uncaught TypeError: Cannot read properties of null (reading 'setAttribute') at register:230:12```
This error can`t appears because that function is disabled.

And you have CORS issue ? 
Please try registering on [The Website](https://wallet.duinocoin.com/register.html).
And using other browser like firefox, ie or edge

**Comment by RezaFauzan945** [comment]
Thanks a lot I have registered and started mining
