### ISSUE TITLE
Incorrect hashrate - what does it mean?

### ISSUE THREAD

**Issue by max-fat** [revoxhere/duco-webservices#40]
got a problem today, why is it not being mined? i use arduino

![2022-02-04_08-36-27](https://user-images.githubusercontent.com/24736761/152478071-b4d17057-9114-469a-afd2-c9ae4062dc81.png)

**Comment by max-fat** [comment]
![2022-02-08_10-22-46](https://user-images.githubusercontent.com/24736761/152937935-cd50f08f-39a3-4bed-95c0-9c216f57b4ce.png)

**Comment by JK-Rolling** [comment]
nothing to worry about and it'll mine as usual. official Arduino_Code hashrate is about 260H/s. the `Incorrect hashrate` message is trying to tell you the hashrate is not within expected range. 225 < hashrate < 270

**Comment by max-fat** [comment]
but when the hashrate is incorrect, I don't get mining
