### ISSUE TITLE
Regestration fails E-mail is not accepted

### ISSUE THREAD

**Issue by 53845714nF** [revoxhere/duco-webservices#48]
I have now tested several of my emails.
Unfortunately all of them fail. The mail providers are gmail and web.de.
In the email names are numbers and also special characters 

I always get this error: "This e-mail address is disposable or invalid. Please try again"

Best

**Comment by revoxhere** [comment]
Hello, please try again now

**Comment by 53845714nF** [comment]
Thank you very much it works.
