### ISSUE TITLE
[Bug] Infinity hashrate

### ISSUE THREAD

**Issue by dimaguy** [revoxhere/duco-webservices#56]
When a miner reports an hashrate of infinity(samsung galaxy ace on opera mini), it breaks the dashboard as it complains it is not being fed the right json on javascript console:
Uncaught (in promise) SyntaxError: Unexpected token 'I', ..."hashrate":Infinity,""... is not valid JSON
It also does not make the error clear enough and locks the user on login page

**Comment by revoxhere** [comment]
Fixed.
