### ISSUE TITLE
Integration into website

### ISSUE THREAD

**Issue by vpts1202** [revoxhere/duco-webservices#69]
Hello
Could you please provide mining script/code for your web miner that I can integrate into my website for browser/web mining?
Thanks.

**Comment by FujaTyping** [comment]
You mean this?
- https://github.com/revoxhere/duco-webservices/blob/master/webminer.html
- https://github.com/revoxhere/duco-webservices/tree/master/js/webminer

**Comment by vpts1202** [comment]
I am looking for something like this: ### https://github.com/NoozAbooz/Duinotize
The things that prevent me to use it are that a) The author @NoozAbooz him self is pointed out that this is kind of beta version b) its always better to direct by native sources(i.e. @revoxhere)

Thanks
